### ISSUE TITLE
Добавяне във F-Droid

### ISSUE THREAD

**Issue by cajeiri** [chitanka/android#15]
Би ли било възможно да се добави, @n0m0r3pa1n ?

https://reports.exodus-privacy.eu.org/en/reports/124616/
За да бъде възможно ще трябва да се замени crashlytics с ACRA и да се махне Flurry връзката.

**Comment by n0m0r3pa1n** [comment]
Здравейте,
Да. Мога да поработя върху това. Ще пиша като имам време. Ще стане до
седмица - 2.

**Comment by cajeiri** [comment]
Мерси за отговора, когато имаш време, стига да стане бих се радвал :)

Забравих да добавя, че е хубаво да се спазва Fastlane файловата система, ако не е така към момента. Ако имаш някакви въпроси спрямо това и други неща, с удоволствие ще ти отговоря. Нямам проблем и с това да пусна апликацията за добавяне, когато горепосочените неща се осъществят, с позволение естествено. Нормално отнема 2-4 седмици най-много за да бъде прегледана и добавена дадена апликация.

**Comment by n0m0r3pa1n** [comment]
С тая история се забавих и то много. Не виждам голямата полза от това да махам крашлитикса, тъй като ми е адски удобно да видя проблемите, които в апа се случват. А в момента са много заради малоумната библиотека за четене на книги, която използвам и в която банда индийци са си оставили ръцете. А и вече е доста морално остарял, нещата много се промениха, тая джава ми е трудно да я гледам вече, бих предпочел да отделя време да го пренапиша.

**Comment by cajeiri** [comment]
@n0m0r3pa1n Няма проблеми, все пак ако решиш да пренаписваш в бъдеще, помисли за използване на ACRA вместо Crashlytics. Повечето апликации просто пускат страничен FOSS вариант без crashlytics, за хората които го искат, с разбирането, че поддръжката там ще е занижена :)
